[env:esp32dev]
platform = espressif32@1.12.4
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
upload_speed = 115200
upload_flags =
    --before
    no_reset
    --after
    hard_reset
    --no-stub

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    bblanchon/ArduinoJson @ ^7.0.0
